version: "3"
services:
    url:
        image: draganczukp/simply-shorten
        container_name: url
        environment:
            # Change if you want to mount the database somewhere else
            # - db_url=/urls.sqlite
            - username=admin
            - password=$3CuReP4S$W0rD
        volumes:
            - db:/urls.sqlite
        restart: unless-stopped

volumes:
    db:

networks:
    proxy:
      external: true
