[package]
name = "simply-shorten"
version = "4.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-files = "0.6.2"
rusqlite = "0.29.0"
regex = "1.7.3"
rand = "0.8.5"
actix-session = {version = "0.7.2", features = ["cookie-session"]}
