[package]
name = "simply-shorten"
version = "4.1.0"
edition = "2021"
authors = ["Sayantan Santra <sayantan[dot]santra689[at]gmail[dot]com"]
license = "MIT"
description = "A simple selfhosted URL shortener with no unnecessary features."
homepage = "https://github.com/SinTan1729/simply-shorten"
documentation = "https://github.com/SinTan1729/simply-shorten"
repository = "https://github.com/SinTan1729/simply-shorten"
readme = "README.md"
keywords = ["docker", "rust", "self-hosted", "url-shortener", "webapp", "shortener", "link-shortener", "actix-web"]
categories = ["web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-files = "0.6.2"
rusqlite = "0.29.0"
regex = "1.7.3"
rand = "0.8.5"
actix-session = {version = "0.7.2", features = ["cookie-session"]}
env_logger = "0.10.0"
